### ISSUE TITLE
ConnectionRefusedError: [Errno 111] 

### ISSUE THREAD

**Issue by Dyson-c** [delta-mpc/python-psi#12]
![image](https://user-images.githubusercontent.com/68522810/187448107-8a6e9cee-6f98-4407-9227-dcf82242243b.png)
[dyson@centos7 python-psi]$ PSI_CONFIG=config/server.config.yaml psi_run server 127.0.0.1:2345
Traceback (most recent call last):
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/pair/socket/pair.py", line 75, in _connect
    client_sock.connect(self._peer)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dyson/.local/bin/psi_run", line 11, in <module>
    load_entry_point('delta-psi==0.0.2', 'console_scripts', 'psi_run')()
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/main.py", line 52, in main
    start_server(args.address)
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/server.py", line 18, in start_server
    with make_pair(local_address, peer_address) as pair:
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/pair/factory.py", line 13, in make_pair
    return SocketPair(local, peer, timeout)
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/pair/socket/pair.py", line 62, in __init__
    self._sock = self._connect(timeout * 3)
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/pair/socket/pair.py", line 100, in _connect
    sock, addr = server_thread.get_sock_addr(timeout=end - now)
  File "/home/dyson/.local/lib/python3.7/site-packages/psi/pair/socket/pair.py", line 49, in get_sock_addr
    return self._res_queue.get(block=block, timeout=timeout)
  File "/usr/local/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

How to solve this problem?

**Comment by big-Cat-123** [comment]
Did you solve it, I also had the same problem

**Comment by shohoku3** [comment]
Unfortunately I didn't. I chose another PSI component


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月4日 13:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [delta-mpc/python-psi] ConnectionRefusedError: [Errno 111] (Issue #12)


Did you solve it, I also had the same problem

―
